language: php

os: linux

addons:
  firefox: "47.0.1"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

services:
 - mysql
 - postgresql
 - docker

jobs:
  include:
    - php: 7.4
      env: MOODLE_BRANCH=master           DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=master           DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli

    - php: 7.3
      env: MOODLE_BRANCH=master           DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=master           DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

    - php: 7.2
      env: MOODLE_BRANCH=master           DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=master           DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd || true
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || true
  - moodle-plugin-ci phpdoc || true
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat

after_success:
  - moodle-plugin-ci coveralls-upload
