language: php

sudo: true

addons:
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.0
 - 7.1
 - 7.2
 - 7.3

services:
 - mysql

env:
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - DB=pgsql MOODLE_BRANCH=master
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - DB=mysqli MOODLE_BRANCH=master

matrix:
 exclude:
  - php: 7.0
    env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 7.0
    env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
  - php: 7.0
    env: DB=pgsql MOODLE_BRANCH=master
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd || true
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker || true
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || true
  - moodle-plugin-ci phpdoc || true
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --dump
